Our-Leaders/our-leaders-api

- models/Politician.js
- models/index.js
- Creates the politician model.
> closes #12730266 | Politician Model

- models/Tag.js
- models/index.js
> closes #12730271 | Tags Model

- controllers/Auth.js
- routes/AuthRoutes.js
- validators/AuthValidators.js
Add support for registered users to login via `POST` request to `/api/auth/login` route
> #12731320 Registered user 

- controllers/Politician.js
- middleware/ImageMiddleware.js
- routes/politicianRoutes.js
- validators/PoliticianValidators.js
- Creates a route for adding accomplishments.
> closes #12732986 | Add Accomplishments

- utils/TypeUtil.js
> Bug - Add type util

- controllers/Politician.js
- models/Politician.js
- routes/politicianRoutes.js
- utils/TypeUtil.js
- validators/PoliticianValidators.js
> closes #12735415 | votes

- communications/Email.js
- communications/templates/baseEmailTemplate.hbs
- communications/templates/subscriptionFeed.hbs
- controllers/Feeds.js
- cron/CronScheduler.js
- cron/FeedJobs.js
- cron/SubscriptionJobs.js
- models/Subscription.js
- package.json
- utils/EmailUtil.js
- utils/FeedUtil.js
> #12738061: notify users on subscriptions

- controllers/Statistics.js
- routes/StatisticRoutes.js
- routes/index.js
Adds a statistics endpoint to retrieve data to be displayed on the dashboard as shown in the mockups
> #12756131: admin retrieve stats

- utils/OutputFormatters.js
This adds a `joinedBy` attribute to the user formatter to be used on the frontend
> add joinedBy attribute to user formatter

- models/Politician.js
- validators/PoliticalPartyValidators.js
- validators/PoliticianValidators.js
* Validate status and political party during politician creation
* Add default values for up & down vote in politician model
* Fix issue in political party validator where validation fails if the part has a leader name
> Various changes and bug fixes

- controllers/Users.js
- routes/UserRoutes.js
The column to be sorted can be passed as a query parameter `sort=`
> #12756138: retrieve user list

- controllers/Subscriptions.js
- controllers/Users.js
- routes/SubscriptionRoutes.js
- Quick fix for User typo and politicianId.
> Feature: Quick Fix

- .gitignore
- config/Init.js
- controllers/Jobs.js
- controllers/Pages.js
- controllers/Users.js
- models/Job.js
- models/Page.js
- models/Setting.js
- models/index.js
- routes/JobRoutes.js
- routes/PageRoutes.js
- routes/index.js
- utils/OutputFormatters.js
- also added fixes and updates for the jobs feature based on the mockups
> #12756133: seed default web pages info and get endpoint

- controllers/Politician.js
- middleware/AuthenticationMiddleware.js
- package-lock.json
- routes/politicianRoutes.js
**Note:** There is a serious problem with cloudinary package, the request automatically cancels when it hits the cloudinary package sending an empty response to the user but the politician is still created.
This is needed for [this PR to work](https://github.com/Our-Leaders/our-leaders-admin/pull/5) to work
> Add image upload to create politician route

- middleware/AuthenticationMiddleware.js
- routes/PageRoutes.js
- Remove authentication for retrieving static pages.
- Error fixes.
> Fix: Static Auth Fix

- controllers/Jobs.js
- controllers/Politician.js
> Feature: Small Fixes

- controllers/Transactions.js
> Feature: Transaction Webhook fix

- controllers/Admins.js
- routes/AdminRoutes.js
- Allow Super Admin block/unblock admins.
> Feature: Admin Block

- config/Init.js
- controllers/Politician.js
- models/Politician.js
- models/User.js
- routes/PoliticianRoutes.js
- validators/PoliticianValidators.js
* This updates or creates new educational background, professional background or political background all in one endpoint.
* It also merges all background permissions into one `politicianBackground` permission.
> Add politician background

- controllers/Politician.js
- models/Politician.js
- validators/PoliticianValidators.js
- Change state in politicalBackground to region
> Feature: Change from state to region in political background

- communications/templates/jobApplication.hbs
- communications/templates/jobApplicationReceived.hbs
- controllers/Jobs.js
- routes/JobRoutes.js
- utils/EmailUtil.js
- validators/JobValidators.js
- It creates the route for applying to a job.
> Feature: Applying to a Job

- controllers/Politician.js
- utils/OutputFormatters.js
- validators/PoliticianValidators.js
- Fixes voting implementation.
> Feature: Voting Fix

- controllers/Politician.js
- models/Politician.js
- routes/PoliticianRoutes.js
- validators/PoliticianValidators.js
This PR implements edit and delete accomplishment routes
> Edit and delete accomplishments

- controllers/Users.js
- middleware/ImageMiddleware.js
- models/User.js
- routes/UserRoutes.js
- utils/OutputFormatters.js
- Updates the user update route to take in image upload.
> Feature: User Image Update

- communications/templates/resetRequest.hbs
- controllers/Auth.js
- utils/StringUtil.js
This PR fixes issue with unavailable btoa and atob. It also makes use of jwt token for password reset which expires after 24 hours.
> Forgot password

- controllers/Admins.js
- controllers/Jobs.js
- controllers/PoliticalParties.js
- controllers/Politician.js
- models/Politician.js
- routes/JobRoutes.js
- routes/PoliticalPartyRoutes.js
- utils/OutputFormatters.js
- validators/PoliticianValidators.js
> - Remove religion from Political model
> - Add route for getting single Political Party
> - Add route for getting job categories
> Changes from review

- controllers/Auth.js
- utils/MailChimpUtil.js
- Small change to fix the email sign up process.
> Feature: Email Sign Up Fix

- communications/templates/baseEmailTemplate.hbs
- communications/templates/resetRequest.hbs
- utils/EmailUtil.js
- It fixes the forgot password email.
> Feature: Forgot Password Fix

- communications/Email.js
- communications/templates/contactUs.hbs
- controllers/Support.js
- routes/SupportRoutes.js
- routes/index.js
- utils/EmailUtil.js
- Creates a support route for emails.
> Feature: Support Route / Contact Us Email

- controllers/Users.js
- routes/UserRoutes.js
[Trello task](https://trello.com/c/5rYWOdAb/33-delete-account-not-working)
Backend for https://github.com/Our-Leaders/our-leaders-client/pull/73
> Bug delete account not working

- controllers/Admins.js
- controllers/Users.js
- routes/AdminRoutes.js
- Add route to reactivate admin.
- Add possible query to retrieve deleted admins and users.
> Feature: Archive API Support

- controllers/Statistics.js
- cron/CronScheduler.js
- utils/OutputFormatters.js
1. Fixes the wrong formatting of date while getting visit and signup stats for the admin
2. Fixes the issue where only end date is only being used to retrieve the visit and signup stats
3. Fixes an error in the cron job
> Various ixes

- controllers/Subscriptions.js
- models/Subscription.js
- routes/SubscriptionRoutes.js
This PR is the backend implementation for [Subscribe button dropdown](https://github.com/Our-Leaders/our-leaders-client/pull/79). It:
- adds `email` to subscription type enum
- creates route and controller for unsubscribing from politicians
> Change subscription button to dropdown

- models/User.js
- Remove password as a requirement.
> Feature: Remove Password Requirement

- controllers/Auth.js
> Fix: Password Request Fix

- controllers/Auth.js
> Fix: Reverse

- controllers/Politician.js
- Handles a case of an empty string for socials.
> Feature: Socials Empty String Fix

- models/Politician.js
- Optional date fields for political background
> Feature: Political Background Field Update

- controllers/PoliticalParties.js
- validators/PoliticianValidators.js
- Switch to OR
- Remove required background fields
> Feature: Political Party Search Fix

- controllers/Politician.js
- validators/PoliticianValidators.js
- Makes all background fields optional.
> Feature: Background Fields Optional

- controllers/PoliticalParties.js
- controllers/Politician.js
> Release #1 - September 14, 2020.
